name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set up QEMU (only if you need cross-platform builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Copy .env.example to .env
        run: cp ./integration_tests/.env.example ./integration_tests/.env

      - name: Make integration tests script executable
        run: chmod +x ./integration_tests/scripts/*

      - name: Run integration script
        run: cd integration_tests && npm run test:integration
